### PR TITLE
Update about.html

### PR DESCRIPTION
**Pull request by DerpyAxolotl**
testing random crap

### CODE REVIEW

**Comment by DerpyAxolotl** [comment]
grrrrrr... I will use my knowledge of discussions to harass you.   
squid-swimming-shstk

**Comment by mercuryhexafluoride** [comment]
The squid looks cool

**Comment by DerpyAxolotl** [comment]
nuh uh
common-octopus-close

**Comment by mercuryhexafluoride** [comment]
image

**Comment by mercuryhexafluoride** [comment]
We are going to go fishing with planes

**Pull request closed without merging**
